"""Translate Chinese sub-items to English + output as JSON"""
import json, re

ENG = {
    "remen": {"name": "Hot Picks", "icon": "🔥", "color": "#e74c3c"},
    "roulei": {"name": "Meat", "icon": "🥩", "color": "#c0392b"},
    "dan_nai": {"name": "Eggs & Dairy", "icon": "🥚", "color": "#f39c12"},
    "yulei": {"name": "Fish", "icon": "🐟", "color": "#2980b9"},
    "shuichan": {"name": "Seafood", "icon": "🦐", "color": "#1abc9c"},
    "shucai": {"name": "Vegetables", "icon": "🥬", "color": "#27ae60"},
    "doulei": {"name": "Beans & Tofu", "icon": "🫘", "color": "#8e44ad"},
    "guopin": {"name": "Fruits", "icon": "🍎", "color": "#e67e22"},
    "wugu": {"name": "Grains & Nuts", "icon": "🌾", "color": "#d4a017"},
    "yaoshi": {"name": "Herbs & Medicine", "icon": "🌿", "color": "#2ecc71"},
    "tiaowei": {"name": "Seasonings", "icon": "🧂", "color": "#95a5a6"},
    "zhushi": {"name": "Staples", "icon": "🍚", "color": "#f39c12"},
    "tang_geng": {"name": "Soups", "icon": "🍜", "color": "#e67e22"},
    "liangcai": {"name": "Cold Dishes", "icon": "🥗", "color": "#2ecc71"},
    "xiaochi": {"name": "Street Food", "icon": "🍢", "color": "#e74c3c"},
    "tianpin": {"name": "Desserts", "icon": "🍰", "color": "#e91e63"},
    "yinshi": {"name": "Drinks", "icon": "🥤", "color": "#00bcd4"},
    "caixi": {"name": "Cuisines", "icon": "🌍", "color": "#9b59b6"},
    "pengren": {"name": "Cooking Methods", "icon": "🍳", "color": "#34495e"},
    "kouwei": {"name": "Flavors", "icon": "🌶️", "color": "#e74c3c"},
    "changhe": {"name": "Occasions", "icon": "🎉", "color": "#9b59b6"},
    "jieri": {"name": "Festivals", "icon": "🎄", "color": "#e74c3c"},
    "jiqiao": {"name": "Techniques", "icon": "🔪", "color": "#7f8c8d"},
    "qiju": {"name": "Equipment", "icon": "🍳", "color": "#95a5a6"},
    "yanla": {"name": "Cured & Smoked", "icon": "🥓", "color": "#c0392b"},
    "ganhuo": {"name": "Dried Goods", "icon": "🍄", "color": "#8e44ad"},
    "qingshi": {"name": "Light Meals", "icon": "🥗", "color": "#27ae60"},
    "yexiao": {"name": "Late Night", "icon": "🌙", "color": "#2c3e50"},
    "xiafan": {"name": "Rice Toppers", "icon": "🍚", "color": "#c0392b"},
    "lingshi": {"name": "Snacks", "icon": "🍿", "color": "#e91e63"},
    "lanren": {"name": "Lazy Recipes", "icon": "😴", "color": "#7f8c8d"},
    "chuangyi": {"name": "Creative", "icon": "💡", "color": "#9b59b6"},
    "sushe": {"name": "Dorm Food", "icon": "🏠", "color": "#f39c12"},
}

# English translations for food/ingredient names
TRANS = {
    # ── 热门推荐 ──
    "今日推荐":"Daily Pick", "本周热门":"Weekly Hot", "最新上架":"New Arrivals",
    "人气top":"Top Rated", "限时特辑":"Limited Edition",
    # ── 猪肉 ──
    "排骨":"Pork Ribs","五花肉":"Pork Belly","猪肝":"Pork Liver","猪腰":"Pork Kidney",
    "猪肚":"Pork Stomach","猪蹄":"Pork Trotters","猪耳":"Pig Ear","猪大肠":"Pig Large Intestine",
    "猪舌":"Pork Tongue","里脊":"Pork Tenderloin","肉馅":"Ground Pork","叉烧":"Char Siu BBQ Pork",
    "猪颈肉":"Pork Neck","猪软骨":"Pork Cartilage","猪血":"Pork Blood","猪头肉":"Pig Head Meat",
    "猪板油":"Pork Leaf Fat","猪尾巴":"Pig Tail","猪蹄髈":"Pork Hock","脆皮肉":"Crispy Pork",
    # ── 牛肉 ──
    "牛腩":"Beef Brisket","牛腱":"Beef Shank","牛排":"Beef Steak","牛舌":"Beef Tongue",
    "牛肚":"Beef Tripe","牛尾":"Oxtail","牛筋":"Beef Tendon","牛百叶":"Beef Omassum",
    "肥牛":"Beef Slices","牛肉馅":"Ground Beef","牛脸肉":"Beef Cheek","牛骨髓":"Bone Marrow","牛腱子":"Beef Shin",
    # ── 羊肉 ──
    "羊排":"Lamb Rack","羊腿":"Lamb Leg","羊杂":"Lamb Offal","羊肉串":"Lamb Skewers",
    "羊蝎子":"Lamb Spine","羊蹄":"Lamb Trotters","羊肚":"Lamb Tripe","羊腿肉":"Lamb Leg Meat","涮羊肉":"Hot Pot Lamb",
    # ── 鸡肉 ──
    "鸡腿":"Chicken Leg","鸡翅":"Chicken Wings","鸡胸":"Chicken Breast","鸡爪":"Chicken Feet",
    "鸡胗":"Chicken Gizzard","鸡肝":"Chicken Liver","乌鸡":"Silkie Chicken","童子鸡":"Spring Chicken",
    "整鸡":"Whole Chicken","鸡翅根":"Drumette","琵琶腿":"Chicken Drumstick",
    # ── 鸭肉 ──
    "鸭脖":"Duck Neck","鸭翅":"Duck Wings","鸭胗":"Duck Gizzard","鸭血":"Duck Blood",
    "鸭掌":"Duck Feet","鸭舌":"Duck Tongue","鸭腿":"Duck Leg","烤鸭":"Peking Duck","盐水鸭":"Salted Duck",
    # ── 其他肉类 ──
    "鹅肉":"Goose","鸽子":"Pigeon","兔肉":"Rabbit","驴肉":"Donkey Meat","鹿肉":"Venison",
    "牛蛙":"Bullfrog","鹌鹑":"Quail","蛇肉":"Snake Meat","腊肉":"Chinese Bacon","火腿":"Ham","培根":"Bacon",
    # ── 蛋类 ──
    "鸡蛋":"Egg","鸭蛋":"Duck Egg","鹌鹑蛋":"Quail Egg","咸蛋":"Salted Egg","皮蛋":"Century Egg",
    "鹅蛋":"Goose Egg","鸽子蛋":"Pigeon Egg","卤蛋":"Marinated Egg","茶叶蛋":"Tea Egg","松花蛋":"Preserved Egg",
    "蛋清":"Egg White","蛋黄":"Egg Yolk",
    # ── 奶类 ──
    "牛奶":"Milk","酸奶":"Yogurt","奶酪":"Cheese","黄油":"Butter","奶油":"Cream","炼乳":"Condensed Milk",
    "奶粉":"Milk Powder","芝士":"Cheese","奶油奶酪":"Cream Cheese","马斯卡彭":"Mascarpone",
    "酸奶油":"Sour Cream","淡奶":"Evaporated Milk","椰奶":"Coconut Milk","豆奶":"Soy Milk",
    # ── 淡水鱼 ──
    "草鱼":"Grass Carp","鲫鱼":"Crucian Carp","鲤鱼":"Common Carp","鲈鱼":"Sea Bass","鲶鱼":"Catfish",
    "泥鳅":"Loach","银鱼":"Whitebait","罗非鱼":"Tilapia","黑鱼":"Snakehead","鳜鱼":"Mandarin Fish",
    "武昌鱼":"Blunt Snout Bream","黄骨鱼":"Yellow Catfish","白条鱼":"Whitebait","翘嘴鱼":"Topmouth Culter","红杉鱼":"Red Snapper",
    # ── 海水鱼 ──
    "带鱼":"Ribbonfish","黄鱼":"Yellow Croaker","多宝鱼":"Turbot","鳕鱼":"Cod","三文鱼":"Salmon",
    "金枪鱼":"Tuna","龙利鱼":"Lemon Sole","鲳鱼":"Pomfret","鳗鱼":"Eel","秋刀鱼":"Pacific Saury",
    "沙丁鱼":"Sardine","马鲛鱼":"Mackerel","比目鱼":"Halibut","巴沙鱼":"Basa Fish","石斑鱼":"Grouper","黄花鱼":"Yellow Croaker",
    # ── 其他水产 ──
    "鱿鱼":"Squid","墨鱼":"Cuttlefish","八爪鱼":"Octopus","鱼头":"Fish Head","鱼片":"Fish Fillet",
    "鱼丸":"Fish Ball","鱼籽":"Fish Roe","鱼肚":"Fish Maw","鱼鳔":"Swim Bladder","鱼面":"Fish Noodles",
    # ── 虾类 ──
    "虾":"Shrimp","虾仁":"Peeled Shrimp","龙虾":"Lobster","皮皮虾":"Mantis Shrimp","淡水虾":"Freshwater Shrimp",
    "虾滑":"Shrimp Paste","虾皮":"Dried Shrimp","虾米":"Dried Shrimp","小龙虾":"Crawfish","基围虾":"Whiteleg Shrimp",
    "对虾":"Prawns","北极虾":"Coldwater Shrimp",
    # ── 蟹贝 ──
    "蟹":"Crab","螃蟹":"Crab","贝类":"Shellfish","扇贝":"Scallop","蛤蜊":"Clams","蛏子":"Razor Clam",
    "生蚝":"Oyster","鲍鱼":"Abalone","海螺":"Sea Snail","海胆":"Sea Urchin","花甲":"Clams",
    "螺蛳":"River Snail","田螺":"Field Snail","海瓜子":"Baby Clams","青口":"Mussels","象拔蚌":"Geoduck",
    "带子":"Scallop Meat","贻贝":"Mussels","圣子":"Razor Clam",
    # ── 海味 ──
    "海参":"Sea Cucumber","海带":"Kelp","紫菜":"Seaweed","海蜇":"Jellyfish","干贝":"Dried Scallop","瑶柱":"Conpoy","昆布":"Kombu","螺旋藻":"Spirulina",
    # ── 叶菜 ──
    "白菜":"Chinese Cabbage","包菜":"Cabbage","青菜":"Bok Choy","菠菜":"Spinach","油菜":"You Choy",
    "生菜":"Lettuce","空心菜":"Water Spinach","韭菜":"Chives","蒜苗":"Garlic Sprouts","芹菜":"Celery",
    "香菜":"Cilantro","油麦菜":"Lettuce","茼蒿":"Garland Chrysanthemum","苋菜":"Amaranth Greens",
    "芥蓝":"Chinese Broccoli","荠菜":"Shepherd's Purse","蕨菜":"Fern Shoots","韭菜苔":"Chive Stems",
    "芥菜":"Mustard Greens","儿菜":"Baby Mustard","娃娃菜":"Baby Cabbage",
    # ── 根茎 ──
    "土豆":"Potato","萝卜":"Radish","胡萝卜":"Carrot","山药":"Chinese Yam","芋头":"Taro",
    "洋葱":"Onion","大葱":"Spring Onion","莲藕":"Lotus Root","竹笋":"Bamboo Shoot","芦笋":"Asparagus",
    "秋葵":"Okra","百合":"Lily Bulb","豆苗":"Pea Shoots","红薯":"Sweet Potato","紫薯":"Purple Sweet Potato",
    "木薯":"Cassava","马蹄":"Water Chestnut","芋苗":"Taro Stem","凉薯":"Jicama","地瓜":"Sweet Potato","香芋":"Taro","慈姑":"Arrowhead",
    # ── 茄果 ──
    "番茄":"Tomato","茄子":"Eggplant","黄瓜":"Cucumber","冬瓜":"Winter Melon","南瓜":"Pumpkin",
    "丝瓜":"Luffa","苦瓜":"Bitter Melon","西葫芦":"Zucchini","玉米":"Corn","辣椒":"Chili Pepper",
    "彩椒":"Bell Pepper","杭椒":"Hangzhou Pepper","美人椒":"Beauty Pepper","小米椒":"Bird's Eye Chili","青椒":"Green Pepper","甜椒":"Sweet Pepper",
    # ── 豆荚 ──
    "豆角":"Long Beans","四季豆":"Green Beans","荷兰豆":"Snow Peas","豌豆":"Peas","毛豆":"Edamame",
    "蚕豆":"Fava Beans","豇豆":"Cowpea","扁豆":"Lentils","蛇豆":"Snake Bean","油豆角":"Oil Beans",
    # ── 菌菇 ──
    "蘑菇":"Mushroom","香菇":"Shiitake","金针菇":"Enoki","杏鲍菇":"King Oyster","木耳":"Wood Ear",
    "银耳":"Snow Fungus","平菇":"Oyster Mushroom","茶树菇":"Tea Tree Mushroom","猴头菇":"Lion's Mane",
    "松茸":"Matsutake","牛肝菌":"Porcini","鸡枞菌":"Termite Mushroom","蟹味菇":"Beech Mushroom",
    "白玉菇":"White Beech","虫草花":"Cordyceps Flower","口蘑":"Button Mushroom","草菇":"Straw Mushroom","竹荪":"Bamboo Fungus",
    # ── 其他蔬菜 ──
    "西兰花":"Broccoli","菜花":"Cauliflower","豆芽":"Bean Sprouts","黄花菜":"Day Lily","紫苏":"Perilla",
    "薄荷":"Mint","冰草":"Ice Plant","枸杞叶":"Goji Leaves","南瓜花":"Pumpkin Flower","槐花":"Acacia Flower",
    # ── 豆制品 ──
    "豆腐":"Tofu","嫩豆腐":"Silken Tofu","老豆腐":"Firm Tofu","豆腐干":"Dried Tofu","豆腐皮":"Tofu Skin",
    "腐竹":"Dried Tofu Sticks","千张":"Tofu Sheets","豆腐乳":"Fermented Tofu","豆浆":"Soy Milk",
    "豆芽":"Bean Sprouts","素鸡":"Vegetarian Chicken","豆泡":"Tofu Puffs","油豆腐":"Fried Tofu",
    "豆腐脑":"Tofu Pudding","豆花":"Tofu Flower","内酯豆腐":"Lactone Tofu","冻豆腐":"Frozen Tofu",
    "兰花干":"Lotus Tofu","素火腿":"Vegetarian Ham",
    # ── 豆类 ──
    "黄豆":"Soybean","绿豆":"Mung Bean","红豆":"Red Bean","黑豆":"Black Bean","芸豆":"Kidney Bean",
    "鹰嘴豆":"Chickpea","眉豆":"Cowpea","花豆":"Speckled Bean","赤小豆":"Adzuki Bean",
    # ── 水果 ──
    "苹果":"Apple","香蕉":"Banana","橙子":"Orange","橘子":"Mandarin","草莓":"Strawberry","西瓜":"Watermelon",
    "哈密瓜":"Hami Melon","葡萄":"Grape","提子":"Grape","桃子":"Peach","李子":"Plum","梨":"Pear",
    "枣":"Jujube","桂圆":"Longan","枇杷":"Loquat","杨梅":"Bayberry","桑葚":"Mulberry","柿子":"Persimmon",
    "杏":"Apricot","甘蔗":"Sugarcane","沙糖橘":"Candy Tangerine",
    "芒果":"Mango","菠萝":"Pineapple","荔枝":"Lychee","龙眼":"Longan","火龙果":"Dragon Fruit",
    "柚子":"Pomelo","椰子":"Coconut","牛油果":"Avocado","百香果":"Passion Fruit","榴莲":"Durian",
    "山竹":"Mangosteen","木瓜":"Papaya","释迦":"Sugar Apple","莲雾":"Wax Apple","杨桃":"Star Fruit",
    "菠萝蜜":"Jackfruit","红毛丹":"Rambutan",
    "蓝莓":"Blueberry","猕猴桃":"Kiwi","柠檬":"Lemon","樱桃":"Cherry","石榴":"Pomegranate",
    "柿子":"Persimmon","杏子":"Apricot","山楂":"Hawthorn","无花果":"Fig","蔓越莓":"Cranberry",
    "树莓":"Raspberry","西柚":"Grapefruit","金桔":"Kumquat","青柠":"Lime","西梅":"Prune","黄桃":"Yellow Peach",
    # ── 米类 ──
    "大米":"Rice","小米":"Millet","糯米":"Glutinous Rice","糙米":"Brown Rice","黑米":"Black Rice",
    "紫米":"Purple Rice","薏米":"Job's Tears","香米":"Fragrant Rice","丝苗米":"Simiao Rice",
    "珍珠米":"Pearl Rice","泰国香米":"Jasmine Rice","五常大米":"Wuchang Rice","红米":"Red Rice",
    # ── 面类 ──
    "面粉":"Flour","全麦粉":"Whole Wheat Flour","面条":"Noodles","挂面":"Dried Noodles","意面":"Pasta",
    "米粉":"Rice Noodles","米线":"Rice Vermicelli","粉丝":"Glass Noodles","乌冬面":"Udon",
    "荞麦面":"Soba Noodles","蝴蝶面":"Farfalle","通心粉":"Macaroni","方便面":"Instant Noodles",
    "拉面":"Ramen","手擀面":"Handmade Noodles","碱水面":"Alkaline Noodles","年糕":"Rice Cake",
    # ── 杂粮 ──
    "燕麦":"Oats","荞麦":"Buckwheat","藜麦":"Quinoa","麦片":"Cereal","高粱米":"Sorghum",
    "西米":"Sago","小麦胚芽":"Wheat Germ","大麦":"Barley",
    # ── 坚果 ──
    "花生":"Peanuts","芝麻":"Sesame","核桃":"Walnuts","杏仁":"Almonds","腰果":"Cashews",
    "松子":"Pine Nuts","开心果":"Pistachios","夏威夷果":"Macadamia","碧根果":"Pecans",
    "瓜子":"Sunflower Seeds","南瓜子":"Pumpkin Seeds","核桃仁":"Walnut Kernels","榛子":"Hazelnuts","板栗":"Chestnuts",
    # ── 药材 ──
    "枸杞":"Goji Berries","红枣":"Red Dates","桂圆":"Longan","人参":"Ginseng","西洋参":"American Ginseng",
    "黄芪":"Astragalus","当归":"Angelica","党参":"Codonopsis","阿胶":"Donkey Hide Gelatin",
    "燕窝":"Bird's Nest","银耳":"Tremella","百合":"Lily Bulb","莲子":"Lotus Seed",
    "山药":"Chinese Yam","茯苓":"Poria","陈皮":"Dried Tangerine Peel","菊花":"Chrysanthemum",
    "玫瑰花":"Rose Buds","金银花":"Honeysuckle","甘草":"Licorice","三七":"Panax Notoginseng",
    "天麻":"Gastrodia","石斛":"Dendrobium","灵芝":"Reishi","藏红花":"Saffron","川贝":"Fritillaria",
    "药材炖汤料包":"Herbal Soup Pack",
    # ── 调味品 ──
    "盐":"Salt","酱油":"Soy Sauce","生抽":"Light Soy Sauce","老抽":"Dark Soy Sauce","醋":"Vinegar",
    "陈醋":"Aged Vinegar","白醋":"White Vinegar","料酒":"Cooking Wine","蚝油":"Oyster Sauce",
    "糖":"Sugar","冰糖":"Rock Sugar","白糖":"White Sugar","红糖":"Brown Sugar","蜂蜜":"Honey",
    "蒸鱼豉油":"Steamed Fish Soy Sauce","鱼露":"Fish Sauce","虾油":"Shrimp Sauce","香醋":"Aromatic Vinegar",
    "米醋":"Rice Vinegar","麦芽糖":"Maltose","枫糖浆":"Maple Syrup","味醂":"Mirin",
    "豆瓣酱":"Doubanjiang Chili Bean Paste","黄豆酱":"Yellow Bean Paste","甜面酱":"Sweet Bean Paste",
    "番茄酱":"Ketchup","辣椒酱":"Chili Sauce","辣酱":"Hot Sauce","剁椒":"Chopped Chili","泡椒":"Pickled Chili",
    "芝麻酱":"Sesame Paste","花生酱":"Peanut Butter","蒜蓉辣酱":"Garlic Chili Sauce",
    "XO酱":"XO Sauce","柱候酱":"Chu Hou Paste","叉烧酱":"Char Siu Sauce","海鲜酱":"Hoisin Sauce",
    "排骨酱":"Spare Rib Sauce","沙茶酱":"Satay Sauce","腐乳酱":"Fermented Tofu Sauce",
    "蛋黄酱":"Mayonnaise","沙拉酱":"Salad Dressing","美乃滋":"Mayonnaise","番茄沙司":"Ketchup",
    "干辣椒":"Dried Chili","花椒":"Sichuan Peppercorn","麻椒":"Mala Peppercorn","八角":"Star Anise",
    "桂皮":"Cinnamon","香叶":"Bay Leaf","丁香":"Cloves","小茴香":"Fennel Seeds","孜然":"Cumin",
    "胡椒粉":"Pepper","花椒粉":"Sichuan Pepper Powder","五香粉":"Five Spice","咖喱":"Curry",
    "百里香":"Thyme","迷迭香":"Rosemary","罗勒":"Basil","薄荷":"Mint","芥末":"Mustard",
    "辣椒面":"Chili Powder","十三香":"Thirteen Spices","卤料包":"Braising Spice Pack",
    "白芷":"Angelica","豆蔻":"Cardamom","草果":"Tsaoko","砂仁":"Amomum",
    "鸡精":"Chicken Bouillon","味精":"MSG","淀粉":"Cornstarch","生粉":"Potato Starch",
    "面包糠":"Breadcrumbs","酵母":"Yeast","泡打粉":"Baking Powder","小苏打":"Baking Soda",
    "吉士粉":"Custard Powder","塔塔粉":"Cream of Tartar","吉利丁":"Gelatin","寒天粉":"Agar",
    "澄粉":"Wheat Starch","粘米粉":"Rice Flour","糯米粉":"Glutinous Rice Flour","水饴":"Starch Syrup",
    # ── 主食 ──
    "炒饭":"Fried Rice","盖饭":"Rice Bowl","煲仔饭":"Clay Pot Rice","寿司":"Sushi",
    "饭团":"Rice Ball","糯米饭":"Sticky Rice","竹筒饭":"Bamboo Rice","烩饭":"Risotto",
    "拌饭":"Mixed Rice","石锅拌饭":"Bibimbap","焖饭":"Braised Rice",
    "粥":"Congee","杂粮粥":"Multigrain Congee","皮蛋瘦肉粥":"Century Egg Pork Congee",
    "海鲜粥":"Seafood Congee","南瓜粥":"Pumpkin Porridge","小米粥":"Millet Porridge",
    "八宝粥":"Eight Treasure Porridge","绿豆粥":"Mung Bean Porridge","红豆粥":"Red Bean Porridge",
    "潮汕粥":"Chaoshan Congee","白粥":"Plain Congee","咸粥":"Savory Congee","甜粥":"Sweet Congee",
    "汤面":"Soup Noodles","拌面":"Mixed Noodles","炒面":"Fried Noodles","凉面":"Cold Noodles",
    "热干面":"Hot Dry Noodles","炸酱面":"Zhajiang Noodles","刀削面":"Knife-Cut Noodles",
    "烩面":"Braised Noodles","担担面":"Dan Dan Noodles","燃面":"Spicy Noodles",
    "阳春面":"Yangchun Noodles","葱油拌面":"Scallion Oil Noodles",
    "馒头":"Steamed Bun","花卷":"Scallion Roll","包子":"Baozi","饺子":"Dumplings","煎饺":"Pan-Fried Dumplings",
    "馄饨":"Wonton","抄手":"Wonton","馅饼":"Meat Pie","肉饼":"Meat Pie","烧饼":"Sesame Flatbread",
    "大饼":"Flatbread","春饼":"Spring Pancake","手抓饼":"Scallion Pancake",
    "锅贴":"Potstickers","煎包":"Pan-Fried Bao","生煎包":"Shengjian","灌汤包":"Soup Dumpling",
    "小笼包":"Xiaolongbao","肉夹馍":"Chinese Hamburger","韭菜盒子":"Chive Pie",
    "葱油饼":"Scallion Pancake","千层饼":"Layer Pancake","薄饼":"Thin Pancake","煎饼盒子":"Pancake Box",
    "面包":"Bread","吐司":"Toast","三明治":"Sandwich","披萨":"Pizza","汉堡":"Burger","贝果":"Bagel",
    "可颂":"Croissant","华夫饼":"Waffle","松饼":"Pancake","法棍":"Baguette","牛角包":"Croissant","热狗":"Hot Dog",
    "油条":"Chinese Donut","煎饼果子":"Jianbing","蛋糕":"Cake","发糕":"Steamed Cake","窝头":"Corn Bun",
    "月饼":"Mooncake","青团":"Green Rice Ball","麻花":"Fried Dough Twist",
    "年糕":"Rice Cake","糍粑":"Glutinous Rice Cake","米糕":"Rice Cake","驴打滚":"Rolling Donkey",
    "豆沙包":"Red Bean Bun","奶黄包":"Custard Bun","马拉糕":"Malay Cake",
    "肠粉":"Rice Rolls","烧卖":"Siu Mai","虾饺":"Har Gow",
    # ── 汤羹 ──
    "排骨汤":"Pork Rib Soup","鸡汤":"Chicken Soup","乌鸡汤":"Silkie Chicken Soup","鸭汤":"Duck Soup",
    "鱼汤":"Fish Soup","牛肉汤":"Beef Soup","羊肉汤":"Lamb Soup","鸽子汤":"Pigeon Soup",
    "猪蹄汤":"Trotter Soup","骨头汤":"Bone Broth","牛尾汤":"Oxtail Soup","猪肚汤":"Pork Tripe Soup","大骨汤":"Bone Soup",
    "豆腐汤":"Tofu Soup","蔬菜汤":"Vegetable Soup","番茄汤":"Tomato Soup","酸辣汤":"Hot & Sour Soup",
    "蛋花汤":"Egg Drop Soup","紫菜汤":"Seaweed Soup","菌菇汤":"Mushroom Soup","冬瓜汤":"Winter Melon Soup",
    "味噌汤":"Miso Soup","罗宋汤":"Borscht","奶油蘑菇汤":"Cream of Mushroom","南瓜浓汤":"Pumpkin Soup","玉米浓汤":"Corn Chowder",
    "甜汤":"Sweet Soup","红豆汤":"Red Bean Soup","绿豆汤":"Mung Bean Soup","银耳羹":"Tremella Soup",
    "冰糖雪梨":"Rock Sugar Pear","桃胶雪燕":"Peach Gum Soup","酒酿圆子":"Fermented Rice Balls",
    "银耳莲子羹":"Tremella Lotus Seed Soup","桂花藕粉":"Osmanthus Lotus Root","杏仁茶":"Almond Tea",
    "花生糊":"Peanut Paste","芝麻糊":"Sesame Paste",
    # ── 凉菜 ──
    "拌菜":"Mixed Salad","凉拌黄瓜":"Cucumber Salad","凉拌木耳":"Wood Ear Salad","凉拌三丝":"Three Shred Salad",
    "拍黄瓜":"Smashed Cucumber","皮蛋豆腐":"Century Egg Tofu","凉拌海带丝":"Seaweed Salad",
    "凉拌粉丝":"Glass Noodle Salad","凉拌豆皮":"Tofu Skin Salad","凉拌藕片":"Lotus Root Salad",
    "凉拌金针菇":"Enoki Salad","老虎菜":"Tiger Salad",
    "口水鸡":"Mouthwatering Chicken","白切鸡":"White Cut Chicken","酱牛肉":"Spiced Beef","酱肘子":"Pig Trotter",
    "卤味":"Braising","卤牛肉":"Braised Beef","卤鸡爪":"Braised Chicken Feet","酱鸭":"Soy Duck",
    "卤水拼盘":"Braising Platter","夫妻肺片":"Fuqi Feipian","盐焗鸡":"Salt Baked Chicken",
    "糟卤":"Fermented Rice Sauce","醉蟹":"Drunken Crab","酱骨架":"Spiced Pork Bones",
    "泡菜":"Kimchi","腌菜":"Pickled Vegetables","辣白菜":"Spicy Cabbage","糖蒜":"Sweet Garlic",
    "酸豆角":"Pickled Long Beans","萝卜干":"Dried Radish","泡椒凤爪":"Pickled Chili Chicken Feet",
    "韩式泡菜":"Korean Kimchi","酸黄瓜":"Pickled Cucumber","雪里蕻":"Pickled Mustard Greens","芥菜头":"Pickled Mustard Root",
    "沙拉":"Salad","蔬菜沙拉":"Green Salad","水果沙拉":"Fruit Salad","土豆沙拉":"Potato Salad",
    "鸡蛋沙拉":"Egg Salad","吞拿鱼沙拉":"Tuna Salad","鸡肉沙拉":"Chicken Salad","意面沙拉":"Pasta Salad",
    # ── 小吃/甜品 ── (abbreviated - same pattern for all)
    "春卷":"Spring Rolls","炸串":"Fried Skewers","炸鸡":"Fried Chicken","炸薯条":"French Fries",
    "天妇罗":"Tempura","炸鸡排":"Fried Chicken Cutlet","炸鸡块":"Chicken Nuggets","薯条":"Fries",
    "洋葱圈":"Onion Rings","炸蘑菇":"Fried Mushrooms","可乐饼":"Croquette",
    "烧烤":"BBQ","烤串":"Skewers","烤鱼":"Grilled Fish","烤肉":"Roast Meat","烤羊肉串":"Lamb Skewers",
    "烤鸡翅":"Grilled Wings","烤蔬菜":"Grilled Veggies","烤茄子":"Grilled Eggplant",
    "烤韭菜":"Grilled Chives","烤玉米":"Grilled Corn","烤生蚝":"Grilled Oysters","铁板烧":"Teppanyaki",
    "关东煮":"Oden","麻辣烫":"Mala Tang","麻辣拌":"Mala Mix","臭豆腐":"Stinky Tofu","冒菜":"Mao Cai",
    "钵钵鸡":"Bobo Chicken","冷锅串串":"Cold Skewers","麻辣香锅":"Mala Xiang Guo","辣炒年糕":"Spicy Rice Cakes",
    "凉皮":"Liangpi","凉粉":"Bean Jelly","米皮":"Rice Noodles","酸辣粉":"Sour Spicy Noodles",
    "螺蛳粉":"Luosifen","桂林米粉":"Guilin Rice Noodles","过桥米线":"Crossing Bridge Noodles",
    "重庆小面":"Chongqing Noodles","花甲粉":"Clam Noodles","炒米粉":"Fried Rice Noodles","炒河粉":"Fried Ho Fan",
    "煎饼":"Chinese Crepe","烤冷面":"Grilled Cold Noodles","鸡蛋仔":"Egg Puffs","章鱼烧":"Takoyaki",
    "驴肉火烧":"Donkey Burger","车轮饼":"Wheel Cake","铜锣烧":"Dorayaki",
    # ── 甜品分类 ──
    "奶油蛋糕":"Cream Cake","戚风蛋糕":"Chiffon Cake","海绵蛋糕":"Sponge Cake","慕斯":"Mousse",
    "芝士蛋糕":"Cheesecake","千层蛋糕":"Mille Crepe","杯子蛋糕":"Cupcake","提拉米苏":"Tiramisu",
    "蛋糕卷":"Swiss Roll","纸杯蛋糕":"Cupcake","裸蛋糕":"Naked Cake","磅蛋糕":"Pound Cake",
    "冰淇淋":"Ice Cream","雪糕":"Ice Cream Bar","冰沙":"Slush","刨冰":"Shaved Ice","绵绵冰":"Shaved Snow",
    "炒冰":"Stir-fried Ice","酸奶冰淇淋":"Frozen Yogurt",
    "糖水":"Sweet Soup","红豆沙":"Red Bean Paste","绿豆沙":"Mung Bean Paste",
    "双皮奶":"Double Skin Milk","姜撞奶":"Ginger Milk Curd","杨枝甘露":"Mango Pomelo Sago",
    "烧仙草":"Herbal Jelly","冰粉":"Ice Jelly","芝麻糊":"Sesame Paste","核桃露":"Walnut Drink",
    "芋圆":"Taro Balls","龟苓膏":"Turtle Jelly","杏仁露":"Almond Drink","花生糊":"Peanut Paste","桂花糖水":"Osmanthus Sweet Soup",
    "蛋挞":"Egg Tart","布丁":"Pudding","饼干":"Cookies","曲奇":"Cookies","巧克力":"Chocolate",
    "糖果":"Candy","泡芙":"Cream Puff","马卡龙":"Macaron","慕斯杯":"Mousse Cup","司康":"Scone",
    "瑞士卷":"Swiss Roll","可丽饼":"Crepe","班戟":"Pancake","麻薯":"Mochi","蛋黄酥":"Egg Yolk Pastry","酥皮":"Puff Pastry",
    "汤圆":"Tangyuan","元宵":"Yuanxiao","驴打滚":"Rolling Donkey","桂花糕":"Osmanthus Cake",
    "龙须糖":"Dragon's Beard Candy","豌豆黄":"Pea Cake","绿豆糕":"Mung Bean Cake",
    "荷花酥":"Lotus Pastry","桃酥":"Walnut Cookie","沙琪玛":"Sachima","糖葫芦":"Candied Hawthorn","江米条":"Fried Glutinous Sticks",
    # ── 饮品 ──
    "奶茶":"Milk Tea","珍珠奶茶":"Bubble Tea","奶盖":"Cheese Foam","果茶":"Fruit Tea",
    "奶绿":"Green Milk Tea","波波茶":"Boba Tea","芋泥奶茶":"Taro Milk Tea",
    "港式奶茶":"Hong Kong Milk Tea","泰式奶茶":"Thai Milk Tea",
    "果汁":"Juice","鲜榨果汁":"Fresh Juice","水果茶":"Fruit Tea","柠檬茶":"Lemon Tea",
    "芒果汁":"Mango Juice","椰子水":"Coconut Water","西瓜汁":"Watermelon Juice",
    "百香果茶":"Passion Fruit Tea","葡萄汁":"Grape Juice","西柚汁":"Grapefruit Juice","青柠汁":"Lime Juice",
    "咖啡":"Coffee","拿铁":"Latte","美式":"Americano","卡布奇诺":"Cappuccino","冰美式":"Iced Americano",
    "摩卡":"Mocha","澳白":"Flat White","冷萃咖啡":"Cold Brew","手冲咖啡":"Pour Over",
    "浓缩咖啡":"Espresso","生椰拿铁":"Coconut Latte","燕麦拿铁":"Oat Latte",
    "茶":"Tea","绿茶":"Green Tea","红茶":"Black Tea","乌龙茶":"Oolong","普洱茶":"Pu'er",
    "花茶":"Flower Tea","铁观音":"Tieguanyin","龙井":"Longjing","碧螺春":"Biluochun",
    "毛尖":"Maojian","白茶":"White Tea","黑茶":"Dark Tea","茉莉花茶":"Jasmine Tea","桂花茶":"Osmanthus Tea",
    "奶昔":"Milkshake","冰沙":"Smoothie","气泡水":"Sparkling Water","可乐":"Cola","雪碧":"Sprite",
    "酒酿":"Fermented Rice","米酒":"Rice Wine","杏仁露":"Almond Milk","椰奶":"Coconut Milk",
    "苏打水":"Soda Water","鸡尾酒":"Cocktail","莫吉托":"Mojito","热巧克力":"Hot Chocolate","酸梅汤":"Sour Plum Drink",
    # ── 菜系 ──
    "川菜":"Sichuan","湘菜":"Hunan","粤菜":"Cantonese","鲁菜":"Shandong","徽菜":"Anhui",
    "闽菜":"Fujian","浙菜":"Zhejiang","苏菜":"Jiangsu","淮扬菜":"Huaiyang","东北菜":"Dongbei",
    "西北菜":"Northwest","陕西菜":"Shaanxi","云南菜":"Yunnan","贵州菜":"Guizhou","湖北菜":"Hubei",
    "江西菜":"Jiangxi","上海菜":"Shanghai","北京菜":"Beijing","天津菜":"Tianjin","客家菜":"Hakka",
    "潮州菜":"Chaozhou","本帮菜":"Shanghai","清真菜":"Halal",
    "港式":"Hong Kong","台湾菜":"Taiwanese","日料":"Japanese","韩餐":"Korean","泰餐":"Thai",
    "西餐":"Western","意大利菜":"Italian","法餐":"French","东南亚菜":"Southeast Asian","印度菜":"Indian",
    "墨西哥菜":"Mexican","中东菜":"Middle Eastern","西班牙菜":"Spanish","越南菜":"Vietnamese",
    "新加坡菜":"Singaporean","马来菜":"Malaysian",
    # ── 烹饪方式 ──
    "炒":"Stir-fry","爆炒":"Quick Stir-fry","滑炒":"Smooth Stir-fry","小炒":"Quick Fry",
    "干煸":"Dry-fry","生炒":"Raw Stir-fry","熟炒":"Precooked Stir-fry","清炒":"Plain Stir-fry",
    "蒸":"Steam","清蒸":"Plain Steam","粉蒸":"Rice Flour Steam","煮":"Boil","水煮":"Water-Boil",
    "白灼":"Blanch","涮":"Dip Boil","隔水蒸":"Double Boil","汽锅":"Steam Pot","炖煮":"Braise","隔水炖":"Double Boil",
    "炸":"Deep-fry","酥炸":"Crispy Fry","煎":"Pan-fry","生煎":"Raw Pan-fry","香煎":"Golden Fry",
    "酥皮":"Puff Pastry","干炸":"Dry Fry","软炸":"Soft Fry","脆炸":"Crispy Fry","软煎":"Soft Pan-fry","裹粉炸":"Coated Fry",
    "烤":"Roast","烤箱":"Oven Bake","烘焙":"Bake","空气炸锅":"Air Fry","炖":"Braise","红烧":"Red Braise",
    "焖":"Stew","炖菜":"Stew","焗":"Bake in Pot","煲":"Clay Pot","烩":"Stew","慢炖":"Slow Cook",
    "煨":"Simmer","盐焗":"Salt Bake","铁板":"Teppan","干锅":"Dry Pot","砂锅":"Clay Pot","啫啫煲":"Clay Pot",
    "拌":"Mix","凉拌":"Cold Mix","腌":"Pickle","卤":"Braise","熏":"Smoke","腊":"Cure","风干":"Air Dry",
    "烟熏":"Smoke","糖渍":"Candied","盐渍":"Salted","糟卤":"Fermented Rice Sauce","酒醉":"Wine Soaked",
    # ── 口味 ──
    "清淡":"Light","咸鲜":"Savory","咸香":"Savory Aroma","甜味":"Sweet","原味":"Original",
    "鲜甜":"Sweet Fresh","咸甜":"Salty Sweet","香辣":"Spicy Aroma","麻辣":"Mala","酸辣":"Sour Spicy",
    "甜辣":"Sweet Spicy","微辣":"Mild","中辣":"Medium","特辣":"Extra Spicy","糊辣":"Burnt Chili",
    "酸甜":"Sweet Sour","糖醋":"Sweet Sour","鱼香":"Yu Xiang","宫保":"Kung Pao","椒盐":"Salt Pepper",
    "蒜香":"Garlic","葱香":"Scallion","酱香":"Soy Aroma","五香":"Five Spice","咖喱":"Curry",
    "黑椒":"Black Pepper","照烧":"Teriyaki","蜜汁":"Honey","茄汁":"Tomato Sauce",
    "蒜蓉":"Garlic Paste","蒜泥":"Mashed Garlic","葱油":"Scallion Oil","红油":"Chili Oil",
    "怪味":"Strange Flavor","胡辣":"Burned Spicy","藤椒":"Green Sichuan Pepper","豆豉":"Fermented Black Beans",
    "蚝油":"Oyster Sauce","姜葱":"Ginger Scallion","避风塘":"Typhoon Shelter",
    "芝士":"Cheesy","奶香":"Milky","抹茶":"Matcha","巧克力":"Chocolate","香草":"Vanilla",
    "肉桂":"Cinnamon","朗姆":"Rum","红酒":"Red Wine","白酱":"White Sauce","青酱":"Pesto","红酱":"Tomato Sauce",
    # ── 场合 ──
    "早餐":"Breakfast","早午餐":"Brunch","午餐":"Lunch","晚餐":"Dinner","下午茶":"Afternoon Tea",
    "夜宵":"Late Night","加餐":"Extra Meal","快手餐":"Quick Meal","懒人餐":"Lazy Meal",
    "上班族":"Office Workers","学生党":"Students","一人食":"Solo Dining","二人食":"Couple Dining",
    "减脂餐":"Diet Meals","孕妇餐":"Pregnancy Meals","儿童餐":"Kids Meals","老人餐":"Elderly Meals",
    "素食者":"Vegetarian","健身餐":"Fitness Meals","月子餐":"Postpartum Meals","哺乳餐":"Nursing Meals",
    "家庭聚餐":"Family Dinner","宴客":"Banquet","聚会":"Party","野餐":"Picnic","露营":"Camping",
    "便当":"Bento","火锅聚餐":"Hot Pot Party","下午茶聚会":"Tea Party","自助餐":"Buffet",
    "年夜饭":"NYE Dinner","春节":"Spring Festival","中秋":"Mid-Autumn","端午":"Dragon Boat",
    "元宵节":"Lantern Fest","情人节":"Valentine's","生日":"Birthday","元旦":"New Year",
    "国庆":"National Day","五一":"Labor Day","万圣节":"Halloween","感恩节":"Thanksgiving","圣诞节":"Christmas",
    # ── 节日 ──
    "年夜饭":"New Year's Eve Dinner","春节":"Spring Festival","元宵节":"Lantern Festival",
    "汤圆":"Tangyuan","端午节":"Dragon Boat Festival","粽子":"Zongzi",
    "中秋节":"Mid-Autumn Festival","月饼":"Mooncake","重阳节":"Double Ninth","冬至":"Winter Solstice",
    "腊八节":"Laba Festival","腊八粥":"Laba Porridge","清明节":"Qingming","青团":"Green Rice Ball",
    "七夕":"Qixi","乞巧果":"Qiqiao Fruit",
    "母亲节":"Mother's Day","父亲节":"Father's Day","生日宴":"Birthday Banquet",
    "万圣节":"Halloween","圣诞节":"Christmas","跨年":"New Year's Eve","新年":"New Year",
    # ── 烹饪技巧 ──
    "刀工":"Knife Skills","切丝":"Julienne","切片":"Slice","切丁":"Dice","雕花":"Carving",
    "切块":"Chunk","剁":"Chop","拍":"Smash","切条":"Cut into Strips","切段":"Cut into Sections",
    "火候":"Heat Control","掌握火候":"Heat Mastery","大火":"High Heat","小火":"Low Heat",
    "中火":"Medium Heat","文火":"Gentle Heat","武火":"High Heat","控温":"Temperature Control",
    "调味":"Seasoning","调味技巧":"Seasoning Tips","腌制":"Marinate","去腥":"Deodorize",
    "码味":"Base Season","挂汁":"Glaze","勾芡":"Thicken",
    "焯水":"Blanch","过油":"Oil Blanch","挂糊":"Batter Coat","上色":"Color",
    "解冻":"Thaw","泡发":"Rehydrate","焯烫":"Blanch Quick","飞水":"Blanch","出骨":"Debone","涨发":"Rehydrate",
    "发面":"Proof Dough","揉面":"Knead","醒面":"Rest Dough","和面":"Mix Dough","打发":"Whip",
    "裱花":"Pipe","擀皮":"Roll Wrapper","包馅":"Fill","造型":"Shape","开酥":"Laminate","酥皮":"Puff Pastry",
    "摆盘":"Plate","装饰":"Garnish","淋汁":"Drizzle Sauce","撒料":"Sprinkle","盛器":"Serveware","盘饰":"Plate Decoration",
    # ── 器具 ──
    "炒锅":"Wok","不粘锅":"Non-stick Pan","铁锅":"Iron Wok","蒸锅":"Steamer","蒸笼":"Bamboo Steamer",
    "砂锅":"Clay Pot","炖盅":"Double Boiler","火锅":"Hot Pot","铸铁锅":"Cast Iron Pot",
    "雪平锅":"Japanese Pot","汤锅":"Stock Pot","奶锅":"Saucepan","平底锅":"Frying Pan","塔吉锅":"Tagine",
    "电饭煲":"Rice Cooker","电压力锅":"Pressure Cooker","烤箱":"Oven","空气炸锅":"Air Fryer",
    "微波炉":"Microwave","面包机":"Bread Maker","厨师机":"Stand Mixer","破壁机":"Blender",
    "豆浆机":"Soy Milk Maker","榨汁机":"Juicer","咖啡机":"Coffee Machine","多士炉":"Toaster",
    "华夫饼机":"Waffle Maker","酸奶机":"Yogurt Maker","电炖锅":"Slow Cooker","电蒸锅":"Electric Steamer","冰淇淋机":"Ice Cream Maker",
    "烤盘":"Baking Tray","打蛋器":"Whisk","料理机":"Food Processor","多功能锅":"Multi Pot",
    "烘焙模具":"Baking Mold","裱花嘴":"Piping Tip","厨房秤":"Kitchen Scale","量杯":"Measuring Cup",
    "筛网":"Sieve","擀面杖":"Rolling Pin","硅胶刮刀":"Silicone Spatula",
    # ── 腌腊 ──
    "腊肉":"Chinese Bacon","腊肠":"Chinese Sausage","腊鸭":"Cured Duck","腊鱼":"Cured Fish",
    "腊猪脸":"Cured Pork Face","腊排骨":"Cured Ribs","腊牛肉":"Cured Beef","腊鸡":"Cured Chicken",
    "腊鹅":"Cured Goose","腊猪蹄":"Cured Trotter","腊舌":"Cured Tongue",
    "熏肉":"Smoked Meat","熏鱼":"Smoked Fish","熏鸡":"Smoked Chicken","熏鸭":"Smoked Duck",
    "烟肉":"Smoked Bacon","熏干":"Smoked Tofu","熏蛋":"Smoked Egg",
    "风干肉":"Air-dried Meat","肉干":"Dried Meat","肉松":"Pork Floss","牛肉干":"Beef Jerky",
    "猪肉脯":"Dried Pork","鱿鱼丝":"Dried Squid","鳗鱼干":"Dried Eel","牛肉粒":"Beef Jerky Bites","鱼干":"Dried Fish",
    "咸肉":"Salted Pork","咸鱼":"Salted Fish","咸鸭蛋":"Salted Duck Egg","咸菜":"Salted Veg",
    "腌萝卜":"Pickled Radish","酸豆角":"Pickled Beans","咸鸡":"Salted Chicken","咸草鱼":"Salted Grass Carp","咸黄鱼":"Salted Yellow Croaker",
    # ── 干货 ──
    "干香菇":"Dried Shiitake","干木耳":"Dried Wood Ear","干银耳":"Dried Tremella",
    "干茶树菇":"Dried Tea Tree Mushroom","干猴头菇":"Dried Lion's Mane","干牛肝菌":"Dried Porcini",
    "干松茸":"Dried Matsutake","干竹荪":"Dried Bamboo Fungus",
    "干鱿鱼":"Dried Squid","干海参":"Dried Sea Cucumber","干鲍鱼":"Dried Abalone",
    "干鱼胶":"Dried Fish Maw","干牡蛎":"Dried Oyster","蛤蜊干":"Dried Clams",
    "粉条":"Vermicelli","干豆皮":"Dried Tofu Skin","干豆腐丝":"Dried Tofu Shreds",
    "蕨根粉":"Fern Root Noodles","宽粉":"Wide Noodles","苕粉":"Sweet Potato Noodles",
    "红薯粉":"Sweet Potato Noodles","魔芋丝":"Konjac Noodles",
    "桂圆干":"Dried Longan","红枣干":"Dried Red Dates","枸杞":"Goji Berries",
    "葡萄干":"Raisins","蜜饯":"Preserved Fruit","蔓越莓干":"Dried Cranberries",
    "蓝莓干":"Dried Blueberries","无花果干":"Dried Figs","杏干":"Dried Apricots","桃干":"Dried Peaches",
    # ── 轻食 ──
    "蔬菜沙拉":"Green Salad","水果沙拉":"Fruit Salad","鸡肉沙拉":"Chicken Salad",
    "牛油果沙拉":"Avocado Salad","凯撒沙拉":"Caesar Salad","藜麦沙拉":"Quinoa Salad",
    "虾仁沙拉":"Shrimp Salad","金枪鱼沙拉":"Tuna Salad",
    "全麦三明治":"Whole Wheat Sandwich","燕麦碗":"Oat Bowl","酸奶碗":"Yogurt Bowl",
    "杂粮饭":"Mixed Grains","荞麦面":"Soba","魔芋面":"Konjac Noodles",
    "全麦卷饼":"Whole Wheat Wrap","玉米沙拉碗":"Corn Salad Bowl",
    "鸡胸肉":"Chicken Breast","水煮菜":"Boiled Veg","蒸菜":"Steamed Veg",
    "无油料理":"Oil-free","低卡料理":"Low Calorie","高蛋白":"High Protein",
    "低碳水":"Low Carb","轻断食":"Intermittent Fasting","代餐":"Meal Replacement",
    "素食":"Vegetarian","纯素":"Vegan","蛋奶素":"Lacto-Ovo","素菜":"Vegetarian Dish",
    "斋菜":"Buddhist Veg","全素":"Vegan","素食便当":"Vegan Bento","植物肉":"Plant-based Meat",
    # ── 夜宵 ──
    "毛豆":"Edamame","花生":"Peanuts","拍黄瓜":"Smashed Cucumber","凉拌菜":"Cold Dish",
    "卤味拼盘":"Braising Platter","无骨鸡爪":"Boneless Chicken Feet","香辣田螺":"Spicy Snails",
    "烤串":"Skewers","酒鬼花生":"Drunkard Peanuts","皮蛋":"Century Egg","鸭脖":"Duck Neck",
    "泡面":"Instant Noodles","冷面":"Cold Noodles","炒粉":"Fried Rice Noodles",
    "韩式拉面":"Korean Ramen","砂锅粥":"Clay Pot Congee","小龙虾盖饭":"Crawfish Rice Bowl",
    "火锅":"Hot Pot","麻辣火锅":"Mala Hot Pot","清汤火锅":"Clear Broth Hot Pot",
    "火锅底料":"Hot Pot Base","蘸料":"Dipping Sauce","鸳鸯锅":"Dual Broth Pot",
    "重庆火锅":"Chongqing Hot Pot","潮汕牛肉火锅":"Chaoshan Beef Hot Pot",
    "寿喜锅":"Sukiyaki","椰子鸡火锅":"Coconut Chicken Hot Pot",
    # ── 下饭菜 ──
    "鱼香肉丝":"Yu Xiang Shredded Pork","麻婆豆腐":"Mapo Tofu","回锅肉":"Twice-Cooked Pork",
    "宫保鸡丁":"Kung Pao Chicken","辣子鸡":"Chongqing Chicken","水煮肉片":"Boiled Sliced Pork",
    "红烧肉":"Red Braised Pork","糖醋里脊":"Sweet Sour Pork","干锅花菜":"Dry Pot Cauliflower",
    "土豆烧牛肉":"Potato Beef Stew",
    "番茄炒蛋":"Tomato Egg","青椒肉丝":"Shredded Pork Peppers","肉末茄子":"Minced Pork Eggplant",
    "蒜薹炒肉":"Pork Garlic Scapes","洋葱炒肉":"Onion Pork","尖椒炒蛋":"Pepper Egg",
    "蚝油生菜":"Oyster Sauce Lettuce","醋溜白菜":"Vinegar Cabbage","酸辣土豆丝":"Sour Potato Shreds","蒜蓉炒肉":"Garlic Pork",
    "小炒肉":"Stir-fry Pork","爆炒肥肠":"Stir-fry Intestines","爆炒猪肝":"Stir-fry Liver",
    "爆炒鸡杂":"Stir-fry Gizzards","干煸四季豆":"Dry-fry Green Beans","酸豆角炒肉末":"Pickled Beans Pork",
    "榨菜肉丝":"Pickled Mustard Pork","青椒炒蛋":"Pepper Egg","豆豉炒肉":"Fermented Bean Pork","孜然牛肉":"Cumin Beef",
    "红烧汁":"Braising Sauce","糖醋汁":"Sweet Sour Sauce","鱼香汁":"Yu Xiang Sauce",
    "照烧汁":"Teriyaki Sauce","黑椒汁":"Black Pepper Sauce","宫保汁":"Kung Pao Sauce",
    "蒜蓉酱":"Garlic Sauce","辣椒酱":"Chili Sauce","甜辣酱":"Sweet Chili Sauce","红烧酱":"Braised Sauce",
    # ── 零食 ──
    "牛肉干":"Beef Jerky","猪肉脯":"Dried Pork","肉松":"Pork Floss","鸡胸肉干":"Chicken Jerky",
    "鸡翅尖":"Chicken Tips","鸭脖":"Duck Neck","鸭舌":"Duck Tongue","鸭掌":"Duck Feet",
    "鱿鱼丝":"Dried Squid","鱼干":"Dried Fish",
    "牛轧糖":"Nougat","雪花酥":"Snowflake Crisp","太妃糖":"Toffee","焦糖":"Caramel",
    "棒棒糖":"Lollipop","软糖":"Gummy Candy","马卡龙":"Macaron","饼干":"Cookies","曲奇":"Cookies","布丁":"Pudding","棉花糖":"Marshmallow",
    "爆米花":"Popcorn","薯片":"Chips","炸薯条":"Fries","虾片":"Shrimp Chips",
    "米花糖":"Rice Crisp","锅巴":"Rice Crust","蛋卷":"Egg Roll","蛋挞":"Egg Tart",
    "芝麻球":"Sesame Ball","麻花":"Twists","猫耳朵":"Cat Ear Cookies",
    "蜜饯":"Preserved Fruit","果脯":"Dried Fruit","糖渍水果":"Candied Fruit",
    "话梅":"Preserved Plum","山楂片":"Haw Flakes","山楂糕":"Haw Jelly","陈皮梅":"Tangerine Plum",
    "桂圆干":"Dried Longan","红枣干":"Dried Red Dates","果丹皮":"Fruit Roll","杏脯":"Dried Apricot","李干":"Dried Plum",
    # ── 懒人食谱 ──
    "电饭煲焖饭":"Rice Cooker Rice","电饭煲鸡翅":"Rice Cooker Wings","电饭煲排骨":"Rice Cooker Ribs",
    "电饭煲蛋糕":"Rice Cooker Cake","电饭煲煲仔饭":"Rice Cooker Pot Rice","电饭煲红烧肉":"Rice Cooker Pork",
    "电饭煲焖菜":"Rice Cooker Veg","一锅炖":"One-pot Stew","电饭煲版":"Rice Cooker Style","电饭煲披萨":"Rice Cooker Pizza",
    "快手菜":"Quick Dish","3分钟":"3 Mins","5分钟":"5 Mins","10分钟":"10 Mins","速成":"Quick","即食":"Instant",
    "微波炉菜":"Microwave Dish","微波炉蒸蛋":"Microwave Egg","微波炉烤红薯":"Microwave Sweet Potato",
    "微波炉爆米花":"Microwave Popcorn","微波炉甜品":"Microwave Dessert",
    "凉拌菜":"Cold Dish","沙拉":"Salad","三明治":"Sandwich","饭团":"Rice Ball","寿司":"Sushi",
    "手撕鸡":"Hand-torn Chicken","白灼菜":"Blanched Veg","蘸酱菜":"Dip Veg",
    "冷面":"Cold Noodles","隔夜燕麦":"Overnight Oats","免烤蛋糕":"No-bake Cake","免烤甜品":"No-bake Dessert",
    "半成品菜":"Semi-finished","速冻水饺":"Frozen Dumplings","速冻包子":"Frozen Baozi",
    "火锅食材":"Hot Pot Ingredients","预制菜":"Pre-made Meals","预制料理包":"Meal Kit",
    "即热米饭":"Instant Rice","方便面升级":"Upgraded Noodles","自热火锅":"Self-heating Pot","自热米饭":"Self-heating Rice",
    # ── 创意菜 ──
    "网红菜":"Viral Dish","网红美食":"Viral Food","挑战":"Challenge","爆款":"Trending",
    "抖音美食":"TikTok Food","小红书美食":"Xiaohongshu Food","打卡":"Check-in","潮流":"Trend","刷屏":"Buzz",
    "融合菜":"Fusion","Fusion":"Fusion","新中式":"New Chinese","中西合璧":"East-West","跨界":"Crossover",
    "混搭":"Mix Match","创新料理":"Innovative Cuisine","分子料理":"Molecular Gastronomy","现代中餐":"Modern Chinese",
    "花式摆盘":"Fancy Plating","雕花":"Carving","造型":"Shaping","创意造型":"Creative Shape",
    "颜值高":"Insta-worthy","艺术感":"Artistic","精致":"Refined","小清新":"Aesthetic","可爱":"Cute","卡通便当":"Character Bento",
    "DIY":"DIY","自制":"Homemade","手工":"Handmade","自制酱料":"Homemade Sauce",
    "厨房实验":"Kitchen Experiment","零失败挑战":"Foolproof","治愈系":"Comfort Food",
    "一人食仪式感":"Solo Dining Ritual","露营美食":"Camping Food",
    # ── 宿舍 ──
    "小电锅":"Mini Electric Pot","电煮锅":"Electric Pot","迷你锅":"Mini Pot","一人锅":"Personal Pot",
    "多功能锅":"Multi-function Pot","早餐机":"Breakfast Maker","三明治机":"Sandwich Maker",
    "蒸蛋器":"Egg Steamer","小烤箱":"Mini Oven","迷你烤箱":"Mini Oven",
    "速食":"Instant Food","泡面":"Instant Noodles","螺蛳粉":"Luosifen","酸辣粉":"Sour Spicy Noodles",
    "拌面":"Mixed Noodles","自热锅":"Self-heating Pot","麦片":"Cereal","面包":"Bread",
    "饼干":"Cookies","牛奶":"Milk","酸奶":"Yogurt",
    "煮面":"Cook Noodles","煮饺子":"Cook Dumplings","煮汤圆":"Cook Tangyuan","煮粥":"Cook Congee",
    "煮鸡蛋":"Boiled Egg","煮玉米":"Corn","煮红薯":"Sweet Potato",
    "关东煮":"Oden","麻辣烫":"Mala Tang","小火锅":"Mini Hot Pot",
    "宿舍早餐":"Dorm Breakfast","宿舍午餐":"Dorm Lunch","宿舍晚餐":"Dorm Dinner",
    "宿舍宵夜":"Dorm Late Night","宿舍一人食":"Dorm Solo Meal",
    "限电":"Power Limited","无火烹饪":"No-fire Cooking","不开火":"No Cooking",
    "蒸菜":"Steamed Dish","拌菜":"Mixed Dish",
}

# Build output with translations
SUBS_FLAT = {} # from script above...
# ... keeping same SUBS structure

import os, json

# SUBS dictionary from the previous script (omitted for brevity - we load from existing file)
# Instead, load the current file and just translate the subs
with open(r"C:\Users\kirito\Desktop\每日菜单\chineserecipes\data\categories.json", "r", encoding="utf-8") as f:
    current = json.load(f)

output = {}
total_translated = 0
for cid, cat in current.items():
    eng_cat = ENG.get(cid, {})
    translated_subs = []
    for item in cat.get("subs", []):
        eng = TRANS.get(item, "")
        if eng:
            translated_subs.append(eng)
            total_translated += 1
        else:
            translated_subs.append(item)  # fallback to Chinese
    output[cid] = {
        "name": eng_cat.get("name", cat["name"]),
        "icon": eng_cat.get("icon", "📁"),
        "color": eng_cat.get("color", "#999"),
        "subs": translated_subs
    }

total = sum(len(v["subs"]) for v in output.values())
outpath = r"C:\Users\kirito\Desktop\每日菜单\chineserecipes\data\categories.json"
with open(outpath, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)
print(f"✅ Written {len(output)} categories, {total} items ({total_translated} translated, {total - total_translated} fallback)")
